services:
  # FRONT
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - user
      - game
    networks:
      - app-network
  
  # NGINX
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:${NGINX_HTTP_PORT}"
      - "8443:${NGINX_HTTPS_PORT}"
    depends_on:
      - frontend
      - user
      - game
    networks:
      - app-network

  # Microservices
  user:
    build: ./microservices/usermanagement
    container_name: user-service
    volumes:
      - user_db_data:/app/src/dbSqlite
    ports:
      - "${USER_MANA_PORT}:${USER_MANA_PORT}"
    networks:
      - app-network

  game:
    build: ./microservices/game
    container_name: game-service
    volumes:
      - game_db_data:/app/src/dbSqlite
    ports:
      - "${GAME_PORT}:${GAME_PORT}"
    networks:
      - app-network

  #redis:
  #  image: redis:7-alpine
  #  container_name: redis
  #  restart: always
  #  ports:
  #    - "6380:${REDIS_PORT}"
  #  networks:
  #    - app-network
  
  # ELK Stack - Logging
  elasticsearch:
    build: ./log/elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"
    networks:
      - observability

  # Prometheus & Grafana
  prometheus:
    build: ./metrics/prometheus
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    networks:
      - observability

  grafana:
    build: ./metrics/grafana
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - observability
    depends_on:
      - prometheus

# Volumes
volumes:
  user_db_data:
  game_db_data:
  esdata:
  prometheus_data:
  grafana_data:

# Networks
networks:
  app-network:
  observability: