services:
  # FRONT
  frontend:
    build: ./frontend
    env_file:
      - .env
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - user
      - game
      - game2
    networks:
      - app-network
    volumes:
      - frontend_db_data:/data
      - ./frontend/src:/app/src:cached
      - ./frontend/package.json:/app/package.json:cached
      - ./frontend/tsconfig.json:/app/tsconfig.json:cached
  
  # NGINX
  nginx:
    build: ./nginx
    env_file:
      - .env
    container_name: nginx
    restart: always
    ports:
      #- "8080:${NGINX_HTTP_PORT}"
      - "8443:${NGINX_HTTPS_PORT}"
    depends_on:
      - frontend
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro

  # Microservices
  user:
    build: ./microservices/usermanagement
    env_file:
      - .env
    container_name: user-service
    volumes:
      - user_db_data:/data
      # ⚡ FOR DEV FILE IN SRC NEED TO BE WATCH MODIF
      - ./microservices/usermanagement/src:/app/src:cached
      - ./microservices/usermanagement/package.json:/app/package.json:cached
      - ./microservices/usermanagement/tsconfig.json:/app/tsconfig.json:cached
    ports:
      - "${USER_MANA_PORT}:${USER_MANA_PORT}"
    networks:
      - app-network

  game:
    build: ./microservices/game
    env_file:
      - .env
    container_name: game-service
    volumes:
      - game_db_data:/data
      # ⚡ FOR DEV FILE IN SRC NEED TO BE WATCH MODIF
      - ./microservices/game/src:/app/src:cached
      - ./microservices/game/package.json:/app/package.json:cached
      - ./microservices/game/tsconfig.json:/app/tsconfig.json:cached
    ports:
      - "${GAME_PORT}:${GAME_PORT}"
    networks:
      - app-network

  game2:
    build: ./microservices/game2
    env_file:
      - .env
    container_name: game2-service
    volumes:
      - game2_db_data:/data
      # ⚡ FOR DEV FILE IN SRC NEED TO BE WATCH MODIF
      - ./microservices/game2/src:/app/src:cached
      - ./microservices/game2/package.json:/app/package.json:cached
      - ./microservices/game2/tsconfig.json:/app/tsconfig.json:cached
    ports:
      - "${GAME2_PORT}:${GAME2_PORT}"
    networks:
      - app-network

  #redis:
  #  image: redis:7-alpine
  #  container_name: redis
  #  restart: always
  #  ports:
  #    - "6380:${REDIS_PORT}"
  #  networks:
  #    - app-network
  
  # ELK Stack - Logging
#  elasticsearch:
#    build: ./log/elasticsearch
#    env_file:
#      - .env
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#    ports:
#      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"
#    networks:
#      - observability

  # Prometheus & Grafana
  prometheus:
    build: ./metrics/prometheus
    env_file:
      - .env
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    networks:
      - observability

  grafana:
    build: ./metrics/grafana
    env_file:
      - .env
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - observability
    depends_on:
      - prometheus

#  kibana:
#    build: ./log/kibana
#    env_file:
#      - .env
#    container_name: kibana
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - "${KIBANA_PORT}:${KIBANA_PORT}"
#    depends_on:
#      - elasticsearch
#    networks:
#      - observability
#  
#  logstash:
#    build: ./log/logstash
#    env_file:
#      - .env
#    container_name: logstash
#    volumes:
#      - ./log/logstash/pipeline:/usr/share/logstash/pipeline
#    ports:
#      - "${LOGSTASH_PORT}:${LOGSTASH_PORT}"
#    environment:
#      - LOGSTASH_PIPELINE_YAML_LOCATION=/usr/share/logstash/pipeline/logstash.yml
#    depends_on:
#      - elasticsearch
#    networks:
#      - observability


# Volumes
volumes:
  frontend_db_data:
  user_db_data:
  game_db_data:
  game2_db_data:
  esdata:
  prometheus_data:
  grafana_data:

# Networks
networks:
  app-network:
    driver: bridge
  observability: