global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3001']

  - job_name: 'game-service'
    static_configs:
      - targets: ['game-service:3002']

  - job_name: 'tournament-service'
    static_configs:
      - targets: ['tournament-service:3003']